import com.intellij.uiDesigner.core.*;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.*;

public class GUI
{
    private JPanel mainPanel;
    private JSpinner numAgentsSpinner;
    private JRadioButton neighbors4Radio;
    private JRadioButton neighbors8Radio;
    private JSpinner gridSizeSpinner;
    private JComboBox boundaryTypeComboBox;
    private JCheckBox emotionCheckBox;
    private JCheckBox densityCheckBox;
    private JSlider contrastSlider;
    private JSpinner betaSpinner;
    private JButton runButton;
    private JButton stopButton;
    
    private void createUIComponents()
    {
        numAgentsSpinner = new JSpinner(new SpinnerNumberModel(50000, 0, 50000, 1));
        gridSizeSpinner = new JSpinner(new SpinnerNumberModel(50, 1, 100, 1));
        betaSpinner = new JSpinner(new SpinnerNumberModel(10000, 0, 1000000, 1));
        runButton = new JButton();
        stopButton = new JButton();
        boundaryTypeComboBox = new JComboBox();
        neighbors4Radio = new JRadioButton();
        neighbors8Radio = new JRadioButton();
        emotionCheckBox = new JCheckBox();
        densityCheckBox = new JCheckBox();
        contrastSlider = new JSlider();
        
        numAgentsSpinner.addChangeListener(e -> Main.numAgents = (int) numAgentsSpinner.getValue());
        
        gridSizeSpinner.addChangeListener(e -> Main.gridSize = (int) gridSizeSpinner.getValue());
        
        betaSpinner.addChangeListener(e -> Main.b = (double) betaSpinner.getValue());
        
        runButton.addActionListener(e -> Main.run());
    
        emotionCheckBox.addItemListener(new ItemListener()
        {
            @Override
            public void itemStateChanged(ItemEvent e)
            {
                if(e.getStateChange() == ItemEvent.SELECTED)
                {
                    Main.hasEmotionDisplay = true;
                }
                if(e.getStateChange() == ItemEvent.DESELECTED)
                {
                    Main.hasEmotionDisplay = false;
                }
            }
        });
    
        densityCheckBox.addItemListener(new ItemListener()
        {
            @Override
            public void itemStateChanged(ItemEvent e)
            {
                if(e.getStateChange() == ItemEvent.SELECTED)
                {
                    Main.hasDensityDisplay = true;
                }
                if(e.getStateChange() == ItemEvent.DESELECTED)
                {
                    Main.hasDensityDisplay = false;
                }
            }
        });
        /*
        stopButton.addActionListener(e -> {
            if(Main.emotion != null)
            {
                Main.emotion.removeAll();
            }
            if(Main.density != null)
            {
                Main.density.removeAll();
            }
        });
        
        boundaryTypeComboBox.addActionListener(e ->
        {
            String str = (String) boundaryTypeComboBox.getSelectedItem();
            if(str.equals("Torus"))
            {
                Main.boundaryType = Environment.BoundaryType.TORUS;
            }
            if(str.equals("Reflect"))
            {
                Main.boundaryType = Environment.BoundaryType.REFLECT;
            }
        });
        
        neighbors4Radio.addActionListener(e -> Main.numAdj = 4);
        
        neighbors8Radio.addActionListener(e -> Main.numAdj = 8);
        
        
        
        contrastSlider.addChangeListener(e -> Main.displayContrast = (int) contrastSlider.getValue());
    */
    }
    
    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }
    
    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 3, new Insets(10, 5, 10, 10), -1, 10));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(3, 2, new Insets(10, 10, 10, 10), -1, 15));
        mainPanel.add(panel1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 1,
                false));
        panel1.setBorder(BorderFactory.createTitledBorder("Environment Settings  "));
        final JLabel label1 = new JLabel();
        label1.setText("Boundary Type");
        panel1.add(label1, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Torus");
        defaultComboBoxModel1.addElement("Reflect");
        boundaryTypeComboBox.setModel(defaultComboBoxModel1);
        boundaryTypeComboBox.setToolTipText("Torus: no boundaries (torus shaped environment), reflect: edges are " +
                "bound (box environment)");
        panel1.add(boundaryTypeComboBox, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Grid Size (N x N)");
        panel1.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        gridSizeSpinner.setToolTipText("input x input");
        panel1.add(gridSizeSpinner, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Number of Agents");
        panel1.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        numAgentsSpinner.setToolTipText("Number of agents in simulation");
        panel1.add(numAgentsSpinner, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(2, 3, new Insets(10, 10, 10, 10), -1, 15));
        mainPanel.add(panel2, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 1,
                false));
        panel2.setBorder(BorderFactory.createTitledBorder("Agent Settings  "));
        final JLabel label4 = new JLabel();
        label4.setText("Neighbors");
        panel2.add(label4, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        neighbors8Radio.setFocusPainted(false);
        neighbors8Radio.setText("8");
        neighbors8Radio.setToolTipText("Agents have 8 neighbors: all adjacent cells (including corners)");
        panel2.add(neighbors8Radio, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Beta Value");
        panel2.add(label5, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        betaSpinner.setFocusTraversalPolicyProvider(false);
        betaSpinner.setName("");
        betaSpinner.setToolTipText("Adjust beta value");
        panel2.add(betaSpinner, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        neighbors4Radio.setFocusPainted(false);
        neighbors4Radio.setSelected(true);
        neighbors4Radio.setText("4");
        neighbors4Radio.setToolTipText("Agents have 4 neighbors: up, down, left, right");
        panel2.add(neighbors4Radio, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(2, 3, new Insets(10, 10, 10, 10), -1, 15));
        panel3.setToolTipText("Stops the simulation");
        mainPanel.add(panel3, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 1,
                false));
        panel3.setBorder(BorderFactory.createTitledBorder("Display Settings"));
        final JLabel label6 = new JLabel();
        label6.setText("Display Type");
        panel3.add(label6, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        emotionCheckBox.setFocusPainted(false);
        emotionCheckBox.setSelected(true);
        emotionCheckBox.setText("Emotion");
        emotionCheckBox.setToolTipText("Enable emotion display");
        panel3.add(emotionCheckBox, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        densityCheckBox.setEnabled(true);
        densityCheckBox.setFocusPainted(false);
        densityCheckBox.setSelected(true);
        densityCheckBox.setText("Density");
        densityCheckBox.setToolTipText("Enable density display");
        panel3.add(densityCheckBox, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label7 = new JLabel();
        label7.setText("Contrast");
        panel3.add(label7, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        contrastSlider.setMajorTickSpacing(1);
        contrastSlider.setMaximum(10);
        contrastSlider.setMinimum(1);
        contrastSlider.setPaintLabels(true);
        contrastSlider.setPaintTicks(true);
        contrastSlider.setSnapToTicks(true);
        contrastSlider.setToolTipText("Adjust contrast of density display");
        contrastSlider.setValue(4);
        panel3.add(contrastSlider, new GridConstraints(1, 1, 1, 2, GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, 15));
        mainPanel.add(panel4, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 1,
                false));
        panel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), "",
                TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, this.$$$getFont$$$(null, -1, -1,
                        panel4.getFont()), new Color(-4473925)));
        runButton.setBorderPainted(true);
        runButton.setFocusPainted(false);
        runButton.setHideActionText(false);
        runButton.setText("Run");
        runButton.setToolTipText("Run the simulation");
        panel4.add(runButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        stopButton.setFocusPainted(false);
        stopButton.setText("Stop");
        stopButton.setToolTipText("Stop the simulation");
        panel4.add(stopButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(neighbors4Radio);
        buttonGroup.add(neighbors8Radio);
    }
    
    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont)
    {
        if(currentFont == null)
        {
            return null;
        }
        String resultName;
        if(fontName == null)
        {
            resultName = currentFont.getName();
        }
        else
        {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if(testFont.canDisplay('a') && testFont.canDisplay('1'))
            {
                resultName = fontName;
            }
            else
            {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size :
                currentFont.getSize());
    }
    
    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() { return mainPanel; }
}
